

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/healthcare
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
