name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Backend Build
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Test Backend (optional)
      working-directory: ./backend
      run: npm test || echo "No tests configured"

    # Frontend Build
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    # Docker Build (optional)
    - name: Build Docker Images
      run: docker-compose -f docker-compose.yml build
