name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js with caching for backend & frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # Backend Build
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Test Backend (optional)
        working-directory: ./backend
        run: npm test || echo "No tests configured"

      # Frontend Build
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Docker Build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker/Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build
